java "-Dsl.log.level=INFO" "-Dsl.log.toConsole=true" `
"-Dsl.log.toFile=true" `
"-Dsl.log.filename=customLog.log" `
"-Dsl.workspace=app" `
"-Dsl.featuresData.codeCoverageManagerVersion=v3" `
"-Dsl.otel.enabled=true" `
"-Dsl.otel.loadEmbeddedAgent=true" `
"-Dsl.sendInitFootprints=true" `
"-Dsl.tags=demo" `
"-Dsl.featuresData.enableLineCoverage=false" `
"-Dsl.ignoreAutoGeneratedMethods=false" `
"-Dsl.ignoreMethodsWithoutLineNumbers=false" `
"-Dsl.featuresData.ignoreMethodsWithoutLineNumbers=false" `
"-Dsl.featuresData.ignoreAutoGeneratedMethods=false" `
"-Dsl.includes=i0.sealights.demo.*" `
"-Dsl.token=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL0RFVi1qYXZhMi5hdXRoLnNlYWxpZ2h0cy5pby8iLCJqd3RpZCI6IkRFVi1qYXZhMixuZWVkVG9SZW1vdmUsQVBJR1ctYzM4N2Q5MTYtNDVjOS00MzZiLWE4NzgtNjQ1NDk4YmJmNDIyLDE3MDQyNzc4MzI5NjUiLCJzdWJqZWN0IjoiU2VhTGlnaHRzQGFnZW50IiwiYXVkaWVuY2UiOlsiYWdlbnRzIl0sIngtc2wtcm9sZSI6ImFnZW50IiwieC1zbC1zZXJ2ZXIiOiJodHRwczovL2Rldi1qYXZhMi1ndy5kZXYuc2VhbGlnaHRzLmNvL2FwaSIsInNsX2ltcGVyX3N1YmplY3QiOiIiLCJpYXQiOjE3MDQyNzc4MzJ9.LjFG9jcoZ8rgU7l7dyMS_m0ecEnBHjOjO1Io4oCe6Jk2T3ycTWJZ-XccJmGlK9FHXH0qlgVXoXzdWhKEoecCagzBm0j9qcgFZjSR4RxDbCUqhljRTG0rc2mDQLM78Zc_TrLILxGKWN0fGlBOprPwLjqaroDBq4ZAQ06hvR21Z1VlsA2YnX7j3ODUyF7c-GsTheo5Zr03dX6_ZcnNWAJFsXUv5WTPqMFu2IARDnrO5PVqOCbq-oTmz3TppcCDKxRB9G0mDgUzTJxRYeRvMsW4SDm3M_NPC28BSPkSn5iC-swsTujPdtUxCaOSbqPv2jxK0L2-PC6WBGkBptrcqX4l8w_3WpyVHLkMCpoqJ1I2GOR0msUFPK0p2QVIoDw0bDxTLRLWMjZTDBbjc-Ws73owPeZJqLg4MrBspppM4L4TeAExiwq8HYGA6fMO70WiAyT0DiR2-HxgPEQJobU42DiqDkbSFYbH5zry-2dmUfddDJRK5LXIYDgqI6z0hOLFubOCi6bwK4u1QT4zwu97X5PDqXQ4uIAXXAm5qxxUzrG4tQO7iHhrRyPfi6eqZeJ89hXYd-wMv-bzsk_tFRbPIeFkOZ6NQYKWMGncSU6m7g1WoGp1e-lDLIUipJE7DHSHkqeqkABd1fqRq0jV5-50x5CmrVEsmtPKbTAK3WnUDJDDYwg" `
"-Dsl.labId=integ_develop_gitcalc" `
"-Dsl.buildName=logback-015" `
"-Dsl.branchName=develop" `
"-Dsl.appName=jgitcalc" `
-javaagent:./sl-cd-agent.jar `
-jar app/.jar



# "-Dsl.httpDebugLog=yes"